# -*- mode: python ; coding: utf-8 -*-
"""PyInstaller spec for the Time Manager Windows build (Phase 9).

Build (from the project root, with runtime + build deps installed):

    pyinstaller time-manager.spec --noconfirm --clean

Produces a *portable one-folder bundle* in `dist/TimeManager/` with two
executables sharing one set of libraries:

    TimeManager.exe      console CLI  (--monitor, --status, --security, ...)
    TimeManagerTray.exe  windowed app (tray + dashboard; no console flash —
                         this is what autostart and the watchdog task run)
    _internal/           shared libs + the shipped browser-extension folder

One folder (rather than one file) keeps start-up fast, keeps the extension
folder loadable unpacked, and is the layout that signs well. See
docs/PACKAGING.md.

The spec runs on any OS: a Linux/macOS build of the same spec is the
cross-platform smoke test (`scripts/build_smoke.sh`); Windows-only pieces
(icon, version resource, pywin32 hidden imports) activate only on win32.
"""

import os
import sys
from pathlib import Path

ROOT = Path(SPECPATH).resolve()

# Invocation-independent imports. The PyInstaller *console script* does not
# put the CWD on sys.path (unlike `python -m PyInstaller`), so the project
# root must be added explicitly before `app` is importable. Found by the
# first real Windows build: every earlier verification had used `-m`, which
# masked this.
sys.path.insert(0, str(ROOT))

from app import __version__

is_windows = sys.platform == "win32"

# ------------------------------------------------------------------- version
# Generated fresh on every build from app.__version__ — never drifts.
VER_FILE = ROOT / "build" / "version_info.txt"
VER_FILE.parent.mkdir(exist_ok=True)
ver_tuple = [int(x) for x in __version__.split(".")[:4]] + [0] * (4 - len(__version__.split(".")))
VER_FILE.write_text(
    f"""# UTF-8
# Version resource for Time Manager {__version__} (generated by time-manager.spec).
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers=({ver_tuple[0]}, {ver_tuple[1]}, {ver_tuple[2]}, {ver_tuple[3]}),
    prodvers=({ver_tuple[0]}, {ver_tuple[1]}, {ver_tuple[2]}, {ver_tuple[3]}),
    mask=0x3F, flags=0x0, OS=0x40004, fileType=0x1, subtype=0x0, date=(0, 0),
  ),
  kids=[
    StringFileInfo([
      StringTable('040904B0', [
        StringStruct('CompanyName', 'Time Manager project'),
        StringStruct('FileDescription', 'Time Manager - app/website/game time limits'),
        StringStruct('FileVersion', '{__version__}'),
        StringStruct('InternalName', 'TimeManager'),
        StringStruct('LegalCopyright', 'MIT-style local project; no telemetry'),
        StringStruct('OriginalFilename', 'TimeManager.exe'),
        StringStruct('ProductName', 'Time Manager'),
        StringStruct('ProductVersion', '{__version__}'),
      ])
    ]),
    VarFileInfo([VarStruct('Translation', [1033, 1200])]),
  ]
)
""",
    encoding="utf-8",
)

# --------------------------------------------------------------------- data
datas = [
    # Ships the unpacked extension inside the bundle; `--show-extension-path`
    # tells the user where it is. The agent never modifies it.
    (str(ROOT / "browser-extension"), "browser-extension"),
    # db.py reads the canonical DDL via Path(__file__).with_name(...); frozen
    # __file__ resolves inside _internal, so this lands exactly where the code
    # looks (found by the Linux smoke build - this is why we smoke-build).
    (str(ROOT / "app" / "database" / "schema.sql"), "app/database"),
]

icon_opt = str(ROOT / "assets" / "app.ico") if is_windows else None

# ------------------------------------------------------------ hidden imports
# Lazy, platform-conditional imports that static analysis can miss: the whole
# app/windows layer is imported inside functions so the core stays importable
# off-Windows. pywin32 is bundled only in Windows builds.
hiddenimports = [
    "app.windows.api",
    "app.windows.power",
    "app.windows.startup",
    "app.windows.win_monitor",
    "app.windows.watchdog",
    "app.cli.monitor",
    "app.cli.selftest",
    "app.cli.simulate",
    "app.cli.detector_selftest",
    "app.ui.qt.app",
]
if is_windows:
    hiddenimports += [
        "win32api",
        "win32gui",
        "win32con",
        "win32process",
        "win32timezone",
        "pythoncom",
        "win32com.client",
    ]

# Keep the bundle lean: Qt engines/widgets the app never touches. PySide6's
# hook otherwise pulls a large share of the Qt runtime.
excludes = [
    "pytest",
    "tests",
    "PySide6.QtWebEngineCore",
    "PySide6.QtWebEngineWidgets",
    "PySide6.QtWebChannel",
    "PySide6.QtQml",
    "PySide6.QtQuick",
    "PySide6.QtQuick3D",
    "PySide6.QtCharts",
    "PySide6.QtDataVisualization",
    "PySide6.QtPdf",
    "PySide6.QtPdfWidgets",
    "PySide6.QtSql",
    "PySide6.QtTest",
    "PySide6.QtDesigner",
    "tkinter",
]

a = Analysis(
    [str(ROOT / "packaging" / "entry_console.py")],
    pathex=[str(ROOT)],
    binaries=[],
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=excludes,
    noarchive=False,
)

pyz = PYZ(a.pure)

exe_console = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name="TimeManager",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    console=True,
    icon=icon_opt,
    version=str(VER_FILE) if is_windows else None,
)

exe_tray = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name="TimeManagerTray",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    # Windowed normally (no console flash from autostart / the watchdog).
    # TIME_MANAGER_TRAY_CONSOLE=1 builds it WITH a console: the diagnostic
    # build for "double-click does nothing" cases — running that exe from a
    # terminal shows the exact error the windowed build swallows.
    console=os.environ.get("TIME_MANAGER_TRAY_CONSOLE") == "1",
    icon=icon_opt,
    version=str(VER_FILE) if is_windows else None,
)

coll = COLLECT(
    exe_console,
    exe_tray,
    a.binaries,
    a.datas,
    strip=False,
    upx=False,
    upx_exclude=[],
    name="TimeManager",
)
